version: '3.1'
services:

  db:
    container_name: listof-db
    restart: always
    image: listof-db
    build:
      context: ./db
    volumes:
      - listof-db-volume:/var/lib/postgresql/data
    env_file:
        - ./.env
    networks:
      - default

  graphql:
    container_name: listof-graphql
    restart: always
    image: graphile/postgraphile
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - default
    command: ["postgraphile",
      "--connection", "${DATABASE_URL}",
      "--port", "5433",
      "--schema", "base,public",
      "--default-role", "anonymous",
      "--jwt-secret", "${SECRET_KEY}",
      "--jwt-token-identifier", "base.sys_token",
      "--cors",
      "--watch"]

  app:
    container_name: listof-app
    restart: always
    image: listof-app
    build:
      context: ./app
    env_file:
      - ./.env
    depends_on:
      - graphql
    networks:
      - default
    command: ["npm", "run", "dev"]

  nginx:
    container_name: listof-nginx
    restart: always
    image: nginx:alpine
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/cert.pem:/etc/nginx/cert.pem
      - ./nginx/config/key.pem:/etc/nginx/key.pem
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    networks:
      - default

networks:
  default:
    external:
      name: listof-network

volumes:
  listof-db-volume:
    external: true
