version: '3.1'
services:

  graphql:
    expose:
      - 5433
    ports:
      - 5433:5433

  app:
    volumes:
      - ./app/init/libs:/srv/app/libs
      - ./app/init/src:/srv/app/src
      - ./app/init/index.html:/srv/app/index.html
    command: ["dev"]

  nginx:
    ports:
      - 8080:8080