version: '3.1'
services:

  db:
    container_name: listof-db
    restart: always
    image: listof-db
    build:
      context: ./db
    volumes:
      - listof-db-volume:/var/lib/postgresql/data
    env_file:
        - ./.env
    networks:
      - default

  graphql:
    container_name: listof-graphql
    restart: always
    image: graphile/postgraphile
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - default
    command: ["postgraphile", "--cors", "--connection", "${DATABASE_URL}", "--host", "0.0.0.0", "--port", "5433", "--schema", "base,public", "--watch", "--default-role", "standard", "--jwt-secret", "MIIEowIBAAKCAQEAuABCnzDR7DgXSu1Ro7ijEVAOBBUTBa8AeB2JM9rYmag3pyTUwGe+VuLdDMKe7s6os0vGI5eYkpAzmyXYym4RujjYC2JM3fNoMgjNpIU2vBUbWklloUnYr7pgvcRcr6EIwFUlR5OQLGTa/43lBLFh8aZewYzgNzevicavE430btmLaXWh/jRmoB5dc/ISIXOodHVlQlVnn/l+TYr59hIHewqs2JMr5aXyRpp+cIsx10TVDH47r1kTzm2ouhn5GcTVJ/VJJhNDp/7f9DDvlg+qO9NJlGenJEum/YN2NWpFsjbzaAHAkP4CSWGXSAHO6jLUxgw/f6vNnktzOypk5V9WcQIDAQABAoIBADiUG+hHYsV4GfF4N/pX9AyGyUiIEmlU/pfwvRes252kFDjZInJndCfTapVZ4vUbptQ7IJohK1El9jhm0tqsLddNU2FswKYfCpMYEePc8o+zDc4dc5q80lx2uvifQMDgi4hYpjX0Mgj0mkKqpxliUfO0bL6nSuqvvNJovb0NkXPj+2hn4byclGYxVwak/OHqb3ucczlbJ5EZjh3F2bJhVUYVI2g4P1z9Qql+zHcrpONo/IPg8Uya0OBS3v3US5ANM0F1INVnokZMYFv5OFepWZ/lB8nxCTr5ZhGGw9GIGCw2cr+NxM6t3sTqvq5opE/bD1yk7XncbaVnX9IT65rhdIECgYEA3+FKYgeYM13JIA4Nq1GA1wCxfZ3cenvlowDx6ziYqpdm+r3uMA91aTTAa8oN+eF6Rqn8JOGGo3+DGi+v1Eay+oRDdptqhO04qAjeJaBvh4YdNGgYFYSE60zoZk/Ui0eRVcMjiJen8t+oDgWotAeNMu4VCG2Ugi+RqBO22lyhJb0CgYEA0mZI/+F+NQ2d8F1N8qp04j7ecchEEXg2A3NehtxumD9G5AlsR+Olt22AXI83C0GH47CxLbOMwQ/2DKbUH7AZoyr0xBQNxFhqdzqSqGlBmwVnh1BgziSr/en2w5IZUHdEKwiO5Mk7d1e3qUHZOQ/7HGkJExwgwJX961oDrbZpPMUCgYEAgiVjqk0j62hvzRSeWaNNtK8QfyfPzdxMiE+6UrVZ+oF9OfJDjujNplUmLwMM0OCExqN2krIQJOexfP2Px2U6EmvlFAQRDikhMH3HNjRn4W7Td22z4n5hDrBswV1S/4yhLiv8ciFHXucpuM0NX2qsaJkC3R1moa+piv265IHIpDkCgYAKMWhh9SOvIEzBg1OuaPGmsFMIgiJCEmfTfPhcYjt9Zrthes9jIDU8ELMCSPHquq8BqeK7ixJLnCFYdZCbRGXJkOAwy6PrGjl2M0E9pXPHNdjRJmS6N+6ZK4eH7AEL8+s6hnydut4Fpxs/uO/0IsEQnEoTQe6YRev6Re8dsFOi3QKBgGLYWVUhBnqLjj1T5q2Gkz7pm6P4u9ujA+A3nAmF1Jo2lcywXlNDHeqxXarckqaJKHxks5g/jLzDwCjOz6FTsq1UCMzX4hl6FJr+e+0qFBqGBL4ykZO+F2xdNOp6sOQ2O/pnDssEUYoNDDyFxS+bEDgT4wfZEKJFnUAiITV3qLH2"]

  api:
    container_name: listof-api
    restart: always
    image: listof-api
    build:
      context: ./api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
        - ./.env
    environment:
      FLASK_APP: api.py
      FLASK_RUN_PORT: 5434
      OAUTHLIB_INSECURE_TRANSPORT: 1
      TOKEN_ISSUER: ${HOST_NAME}
      AFTER_LOGIN_REDIRECT: ${HOST_NAME}
    depends_on:
      - graphql
    networks:
      - default
    command: ["flask", "run", "--host=0.0.0.0"]
    secrets:
      - public_key
      - private_key

  app:
    container_name: listof-app
    restart: always
    image: listof-app
    build:
      context: ./app
    volumes:
      - ./app/init:/srv/app
    env_file:
      - ./.env
    depends_on:
      - api
      - graphql
    networks:
      - default
    command: ["npm", "run", "build"]

  nginx:
    container_name: listof-nginx
    restart: always
    image: nginx:alpine
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/cert.pem:/etc/nginx/cert.pem
      - ./nginx/config/key.pem:/etc/nginx/key.pem
    ports:
      - 80:80
      - 443:443
      - 5434:5434
    depends_on:
      - api
      - app
    networks:
      - default

networks:
  default:
    external:
      name: listof-network

volumes:
  listof-db-volume:
    external: true

secrets:
  public_key:
    file: public.pem
  private_key:
    file: private.pem
