version: '3.1'
services:

  test-db:
    container_name: listof-test-db
    image: listof-test-db
    build:
      context: .
      dockerfile: ./test/Dockerfile
    command: ["nose2", "-v", "test_db.TestDb"]
    depends_on:
      - db
    networks:
      - default

  test-api:
    container_name: listof-test-api
    image: listof-test-api
    build:
      context: .
      dockerfile: ./test/Dockerfile
    command: ["nose2", "-v", "test_api.TestApi"]
    depends_on:
      - api
    networks:
      - default

  test-app:
    container_name: listof-test-app
    build:
      context: ./app
    env_file:
      - ./.env
    command: "npm run test && npm run lint"
    image: listof-test-app

networks:
  default:
    external:
      name: listof-network
