version: '3.1'
services:


  db:
    expose:
      - 5432
    ports:
      - 5432:5432

  graphql:
    expose:
      - 5433
    ports:
      - 5433:5433

  api:
    volumes:
      - ./api/init:/srv/api/
    expose:
      - 5434
    environment:
      FLASK_DEBUG: 1

  app:
    volumes:
      - ./app/init/:/srv/app
    expose:
      - 5435
    ports:
      - 5435:8080
    command: ["npm", "run", "dev"]
