version: '3.1'
services:

  db:
    container_name: listof-db
    restart: always
    image: listof-db
    build:
      context: ./db
    volumes:
      - listof-db-volume:/var/lib/postgresql/data
    env_file:
        - ./.env
    networks:
      - default

  graphql:
    container_name: listof-graphql
    restart: always
    image: graphile/postgraphile
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - default
    command: ["postgraphile",
      "--connection", "${DATABASE_URL}",
      "--port", "5433",
      "--schema", "base,public",
      "--default-role", "standard",
      "--jwt-secret", "${SECRET_KEY}",
      "--jwt-token-identifier", "base.sys_token",
      "--cors",
      "--watch"]

  api:
    container_name: listof-api
    restart: always
    image: listof-api
    build:
      context: ./api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
        - ./.env
    environment:
      FLASK_APP: api.py
      FLASK_RUN_PORT: 5434
      OAUTHLIB_INSECURE_TRANSPORT: 1
      TOKEN_ISSUER: ${HOST_NAME}
      AFTER_LOGIN_REDIRECT: ${HOST_NAME}
    depends_on:
      - graphql
    networks:
      - default
    command: ["flask", "run", "--host=0.0.0.0"]
    secrets:
      - public_key
      - private_key

  app:
    container_name: listof-app
    restart: always
    image: listof-app
    build:
      context: ./app
    volumes:
      - ./app/init:/srv/app
    env_file:
      - ./.env
    depends_on:
      - graphql
    networks:
      - default
    command: ["npm", "run", "build"]

  nginx:
    container_name: listof-nginx
    restart: always
    image: nginx:alpine
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/cert.pem:/etc/nginx/cert.pem
      - ./nginx/config/key.pem:/etc/nginx/key.pem
    ports:
      - 80:80
      - 443:443
      - 5434:5434
    depends_on:
      - app
    networks:
      - default

networks:
  default:
    external:
      name: listof-network

volumes:
  listof-db-volume:
    external: true

secrets:
  public_key:
    file: public.pem
  private_key:
    file: private.pem
