version: '3.1'
services:


  db:
    expose:
      - 5432
    ports:
      - 5432:5432

  graphql:
    expose:
      - 5433
    ports:
      - 5433:5433

  app:
    volumes:
      - ./app/init/:/srv/app
    expose:
      - 8080
    ports:
      - 8080:8080
    command: ["npm", "run", "dev"]
